### PR TITLE
Additional parser updates

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Allows function definition

```julia
function f end
```

used to define zero-method generic functions.

`baremodule`s are available in addition to `module`.

Disallows backticks in identifiers, which is need to allow command literals with prefixes which I've implemented here. ~~Related to this: Julia also allows suffixes to both string and command literals, which I've not implemented here. As well as prefixes and suffixes for `"""` strings literals and ` ``` ` command literals. I'll open an issue for this one since I'm not 100% sure the best way to handle these.~~ See #7 for details.

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Failure is on `:local` and `:global` symbols in the Mocha.jl tests. I assumed that those would be separate tokens rather than `(quote_expression (identifier)`.

**Comment by maxbrunsfeld** [comment]
Yeah, it looks like this caused parse errors to occur in a number of files which were previously parsing successfully, fromthe Gadfly, IJulia, and Mocha repositories.

> Failure is on `:local` and `:global` symbols 

It might be that we need to allow `local` and `global` to be used as identifiers, in addition to treating them as keywords. This is something that has come up in a number of other grammars. Usually, we handle it with something like this:

```js
_primary_expression: $ => choice(
  // other choices ...
  $.identifier,
  alias(choice('local', 'global'), $.identifier),
)
```

**Comment by MichaelHatherly** [comment]
Locally it's passing all tests now. Parsing `:` for symbols wasn't causing a bunch of problems elsewhere. Not sure if what I've done is the correct way to handle it though.

**Comment by maxbrunsfeld** [comment]
> Parsing `:` for symbols was causing a bunch of problems elsewhere

What is the advantage of creating a special-case for quoted identifiers? Isn't `:foo` the same as `:(foo)` etc? I would think it should always be parsed as a quote expression.

**Comment by 00sapo** [comment]
I have tested this PR for string macros and found it works for me (even though I now get an error about ABI version.

image

**Comment by MichaelHatherly** [comment]
Very stale, looks like everything here has probably already been addressed by @savq.

**Pull request closed without merging**
