### PR TITLE
Add highlighting queries

### LINKED ISSUE #133: Upstream queries
[Treesitter v0.21.0](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.21.0) made last-wins precedence the default, meaning tree-sitter queries now work in the same order as nvim ~/helix~ queries.

[nvim-treesitter also renamed some captures](https://github.com/nvim-treesitter/nvim-treesitter/pull/5895) to align with tree-sitter and helix. 

This means maintaining a common set of queries is much easier now, it would reduce some duplicated efforts between editors, and also make it easier to handle breaking changes downstream.

### PR DESCRIPTION
**Pull request by savq**
TODO: Remove nvim specific captures.

Closes #133

### CODE REVIEW

**Comment by savq** [comment]
> Do you intend to have this as a kind of editor-agnostic reference?

Yes, the idea is being editor-agnostic and not too opinionated.

The Neovim queries have been the de-facto default, but only because I'm maintaining them. As more editors are using tree-sitter now, maintaining all the queries is becoming a mess:

- Emacs doesn't have a good way to ensure the version of the tree-sitter parser.
- Helix still doesn't support last-pattern-wins precedence. Like they said they would, months ago.
- Sometimes I just forget to update the neovim queries.

Having the queries here solves that.

**Comment by piechologist** [comment]
Sounds good! 

I'll comb through this and Zed's version. Hopefully, I can use this reference and append the Zed specific stuff if precedence allows. That would make it easier to maintain a common set of queries.

**Comment by piechologist** [comment]
Here are the queries that are currently in zed-julia but not in your draft. Hope it's okay to dump it here. Some blocks *are* probably too opinionated for a reference file. You might consider adding a few other ones. 

Captures that need to be changed manually when copying the reference:

1. nvim `@string.documentation` — Zed `@comment.doc`
2. nvim `@character` — Zed `@string`

Queries:

```scm
; Required to highlight the macro name, not just the @
(macro_identifier
  (identifier) @function.macro)

; Parameters, I think we can drop both:
(argument_list
  (identifier) @variable.parameter)

(function_expression
  .
  (identifier) @variable.parameter) ; Single parameter arrow functions

; Interpolated variables and complex expressions
(string_interpolation
[
  "$"
  "("
  ")"
] @punctuation.special)

; Match the dot in the @. macro
(macro_identifier
  (operator) @function.macro (#eq? @function.macro "."))

; Function definitions like `function foo() ...` or `function Base.show() ...`
(signature
  (call_expression
    [
      (identifier) @function.definition
      (field_expression (identifier) @function.definition .)
    ]))

; Short function definitions like `foo(x) = 2x`
(assignment
  .
  [
    (call_expression (identifier) @function.definition)
    (typed_expression . (call_expression (identifier) @function.definition))
    (where_expression . (call_expression (identifier) @function.definition))
    (where_expression . (typed_expression . (call_expression (identifier) @function.definition)))
    (call_expression (field_expression (identifier) @function.definition .))
    (typed_expression . (call_expression (field_expression (identifier) @function.definition .)))
    (where_expression . (call_expression (field_expression (identifier) @function.definition .)))
    (where_expression . (typed_expression . (call_expression (field_expression (identifier) @function.definition .))))
  ]
  (operator) @keyword.function)

; Docstrings
((macrocall_expression
  (macro_identifier "@" (identifier)) @function.macro
  (macro_argument_list
    .
    (string_literal) @comment.doc))
  (#eq? @function.macro "@doc"))

(source_file
  (string_literal) @comment.doc
  .
  [
    (identifier)
    (open_tuple
      (identifier))
  ])

(module_definition
  (string_literal) @comment.doc
  .
  [
    (identifier)
    (open_tuple
      (identifier))
  ])
```

A question: do we need lines 245 and 246 with "=" and "∈" as they already are `(operator)` nodes?

**Comment by clason** [comment]
You probably also want to add injections and locals; these are standard queries following (mostly) upstream format.

On a general note: Some editor customization is and will always be required (mostly around captures and predicates), but I am strongly in favor of having "source of truth" queries live together with the parser, for two reasons:
1. early detection of breaking parser changes (you follow semver, right? _right?!_) together with required changes;
2. avoiding duplicate/divergent downstream work.

(I _really_ wish we had more cooperation on this; Neovim made a significant effort to align with upstream/Helix on queries, but there has been preciously little reciprocation. And don't get me started on Zed, which likes to pretend to be the only editor in the universe using tree-sitter...)

**Comment by savq** [comment]
> A question: do we need lines 245 and 246 with "=" and "∈" as they already are (operator) nodes?

Yes, For loop bindings don't have a visible operator node (I don't remember why... maybe that can be updated so those extra patterns aren't needed).

**Comment by piechologist** [comment]
Oh, those little details... 😅. Thanks for clarifying!

**Comment by savq** [comment]
I'm going to leave out injections because I haven't implemented visible quotation mark nodes, and locals because neovim doesn't highlight them AFAIK.

**Pull request merged**
