### PR TITLE
Typo fix: parametere -> parameters

### PR DESCRIPTION
**Pull request by Honeypot95**
Solves issue #21 .

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for the fix! I think you just need to regenerate the parser with `tree-sitter generate`, rather than making manual edits to `parser.c`.

**Comment by Honeypot95** [comment]
Sorry, I just did a `sed`-like find and replace. I will look into regenerating the parser.

**Comment by Honeypot95** [comment]
So, I did `tree-sitter generate` after changing only `parametere` -> `parameters` in `grammar.js`. For some reasons, the diff got pretty big, as at least one field seems to have been moved around or deleted. The travis build seems to pass, which is good.

**Comment by maxbrunsfeld** [comment]
I think there was already a field called “parameters”, so this change consolidated those two field names into one. Thank you!

**Comment by Honeypot95** [comment]
That seems to have been the case, but using tree-sitter from emacs would not highlight a query with "parameters" as well, just "parametere", which now seems really strange. But I am glad it is solved.

**Pull request merged**
