### PR TITLE
Anonymous fun (fix #12)

### LINKED ISSUE #12: parse error when using `function () end` as an anonymous function
When I input the following
```julia
a = function3(function ()
    return 1
end)
```
I get
```
((source_file
  (assignment_expression
   (identifier)
   (call_expression
    (identifier)
    (argument_list
     (ERROR))))
  (return_statement
   (number))
  (identifier)
  (ERROR))
 . 154)
```
On the other hand, using the `->` notation, the code gets parsed OK, see below.
Input:
```julia
a = function3(()->begin
    return 1
end)
```
Parsed tree
```
((source_file
  (assignment_expression
   (identifier)
   (call_expression
    (identifier)
    (argument_list
     (function_expression
      (parameter_list)
      (compound_expression
       (return_statement
        (number))))))))
 . 186)
```

### LINKED ISSUE #13: empty anonymous function not properly parsed
Input
```julia
Channel(
    c->begin # some comment
    end)
```

Output
```elisp
((source_file
  (call_expression
   (identifier)
   (argument_list
    (function_expression
     (identifier)
     (compound_expression
      (comment)
      (identifier)
      (MISSING "end"))))))
 . 156)
```
If I add anything to the body (say a single line with `1` in it), then it is properly parsed

### PR DESCRIPTION
**Pull request by FelipeLema**
Pretty straightforward. Fixes #12 

I think I'm following conventions on this, lemme know if it isn't so.

### CODE REVIEW

**Comment by FelipeLema** [comment]
are `src/grammar.json` and `src/parser.c` not generated automatically from `grammar.js`?

is there a particular reason for having devs to commit generated files?

**Comment by maxbrunsfeld** [comment]
Yeah, those files are committed to the repo so that users of this repo can use it without having to install the `tree-sitter` CLI.

**Comment by FelipeLema** [comment]
oh, I see, thanks for that explanation.

will probably [add a git hook to add them automagically](https://stackoverflow.com/a/3971851/3637404)

re-uploading them

**Comment by maxbrunsfeld** [comment]
Looks good. Thanks for the fix!

**Pull request merged**
